# Generated by Django 4.2.5 on 2023-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_savings_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repay_period',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_amount',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
